version: "3.9"
services:
  db:
    image: mysql:8.0
    volumes:
      # 初期データ投入
      - ../db/initdb.d:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -proot

  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    volumes:
      - ../api:/usr/api
    ports:
      - "18000:8080"
    tty: true
    # dbが起動してヘルスチェックが通ってから起動する
    depends_on:
      db:
        condition: service_healthy
